### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by matvey19999** [N-Joy-Shadow/MoreTerminal#1]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 22.03.2023, 15:49
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/blakebr0/extendedcrafting/api/crafting/ITableRecipe
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?] {}
	at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?] {}
	at appeng.menu.guisync.DataSynchronization.collectFields(DataSynchronization.java:42) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at appeng.menu.guisync.DataSynchronization.collectFields(DataSynchronization.java:57) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at appeng.menu.guisync.DataSynchronization.<init>(DataSynchronization.java:38) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at appeng.menu.AEBaseMenu.<init>(AEBaseMenu.java:87) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:mixin,re:classloading,pl:mixin:APP:moreterminal.mixins.json:MixinAEBaseMenu,pl:mixin:A}
	at appeng.menu.me.common.MEStorageMenu.<init>(MEStorageMenu.java:162) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at njoyshadow.moreterminal.menu.extendedcrafting.BaseCraftingTermMenu.<init>(BaseCraftingTermMenu.java:60) ~[moreterminal-0.1.jar%2356!/:1.0-SNAPSHOT] {re:classloading}
	at njoyshadow.moreterminal.menu.extendedcrafting.UltimateCraftingTermMenu.<init>(UltimateCraftingTermMenu.java:17) ~[moreterminal-0.1.jar%2356!/:1.0-SNAPSHOT] {re:classloading}
	at appeng.menu.implementations.MenuTypeBuilder.lambda$new$0(MenuTypeBuilder.java:80) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at appeng.menu.implementations.MenuTypeBuilder.lambda$open$1(MenuTypeBuilder.java:171) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at net.minecraft.world.SimpleMenuProvider.m_7208_(SimpleMenuProvider.java:25) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraftforge.network.NetworkHooks.openGui(NetworkHooks.java:202) ~[forge-1.18.2-40.2.0-universal.jar%2363!/:?] {re:classloading}
	at appeng.menu.implementations.MenuTypeBuilder.open(MenuTypeBuilder.java:177) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at appeng.menu.MenuOpener.open(MenuOpener.java:63) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at appeng.menu.MenuOpener.open(MenuOpener.java:52) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at appeng.parts.reporting.AbstractTerminalPart.onPartActivate(AbstractTerminalPart.java:111) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at appeng.parts.AEBasePart.onActivate(AEBasePart.java:361) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at appeng.parts.CableBusContainer.activate(CableBusContainer.java:667) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at appeng.block.networking.CableBusBlock.onActivated(CableBusBlock.java:232) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at appeng.block.AEBaseEntityBlock.m_6227_(AEBaseEntityBlock.java:229) ~[AE2-11.7.0-FORGE-1.18.2.jar%2353!/:11.7.0] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:697) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:342) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:985) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.ClassNotFoundException: com.blakebr0.extendedcrafting.api.crafting.ITableRecipe
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 713878536 bytes (680 MiB) / 2415919104 bytes (2304 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX(tm)-8350 Eight-Core Processor           
	Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
	Microarchitecture: Piledriver
	Frequency (GHz): 3,89
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 970
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x13c2
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3118
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096,00
	Memory slot #2 clockSpeed (GHz): 1,60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096,00
	Memory slot #3 clockSpeed (GHz): 1,60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 31444,72
	Virtual memory used (MB): 23205,93
	Swap memory total (MB): 6912,00
	Swap memory used (MB): 187,55
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Tomka21'/314, l='ServerLevel[Новый мир]', x=181.77, y=64.00, z=-59.92]]
	Data Packs: vanilla, mod:forge, mod:codechickenlib (incompatible), mod:avaritia (incompatible), mod:tlskincape (incompatible), mod:moreterminal (incompatible), mod:ae2 (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18.2-40.2.0-universal.jar                 |Forge                         |forge                         |40.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		codechickenlib-1.18.2-4.1.3.480-universal.jar     |CodeChicken Lib               |codechickenlib                |4.1.3.480           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		avaritia-1.18.2-4.0.1.6-universal.jar             |Avaritia                      |avaritia                      |4.0.1.1             |DONE      |Manifest: NOSIGNATURE
		tl_skin_cape_forge_1.18_1.18.2-1.25.jar           |TLSkinCape                    |tlskincape                    |1.25                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		moreterminal-0.1.jar                              |Moreterminal                  |moreterminal                  |1.0-SNAPSHOT        |DONE      |Manifest: NOSIGNATURE
		AE2-11.7.0-FORGE-1.18.2.jar                       |Applied Energistics 2         |ae2                           |11.7.0              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 9031ad75-ec2e-4640-83f9-0004098c1a10
	FML: 40.2
	Forge: net.minecraftforge:40.2.0

**Comment by myogoo** [comment]
Sorry this project not continued. because i can’t fix jei bug and This brings the overall code of ae2, so it is hard to update every time

**Comment by myogoo** [comment]
if you want to run this mod. set ae2 version 11.6.7 under and add extended crafting table

**Comment by matvey19999** [comment]
Thank you for your help
